spring:
  application:
    name: config-profiles
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: prod

build:
  id: 122
  version: 1.2.0
  name: "default-build"
  type: "default build"
